### ISSUE TITLE
UNBRICK :D

### ISSUE THREAD

**Issue by Zibri** [therealdreg/ftdibrick#4]
Good work. I thought the same today. Any other way to unbrick?

**Comment by therealdreg** [comment]
![image](https://github.com/user-attachments/assets/1badb6ef-43ad-4d27-a43c-824bd6b2370a)

![image](https://github.com/user-attachments/assets/13d5ec3e-f4f3-47b5-b35f-2cffe0edea37)

what eeprom pins? xD

the only way I know: add a clock

@S0S4
